logging:
    pattern:
        console: "[GenAI-RAG] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
        file: "[GenAI-RAG] %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file:
        name: logs/clinicalrag.log
        max-size: 10MB
        max-history: 7
    level:
        org:
            springframework:
                ai:
                    chat:
                        client:
                            advisor: DEBUG

spring:
    application:
        name: genai-rag
    main:
        banner-mode: off
        log-startup-info: false
    neo4j:
        uri: bolt://localhost:7687
        authentication:
            username: neo4j
            password: abcd1234
    ai:
        openai:
            api-key: ${OPENAI_API_KEY} 
            enabled: true  # Disable default Spring AI OpenAI configuration
            chat:
                options:
                    model: gpt-4o-mini
            embedding:
                options:
                    model: text-embedding-3-small
                    encoding-format: float
                    dimensions: 1536
        vectorstore:
            neo4j:
                initialize-schema: true
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres

# Add PingFederate authentication configuration for OpenAI
ping:
    openai:
        client-id: ${PING_CLIENT_ID:your-default-client-id}
        client-secret: ${PING_CLIENT_SECRET:your-default-client-secret}
        token-url: ${PING_TOKEN_URL:https://your-pingfederate-domain/as/token.oauth2}
        api-base-url: ${OPENAI_API_BASE_URL:https://your-api-gateway/api/v1/openai}